Update Datadog SDKs from `v4` => `v5`
RoundingWell/care-ops-frontend pull request #1184
Opened 2023-11-06 22:26 UTC by nmajor25

Shortcut Story ID: [sc-42902]

2023-11-06 22:27 UTC, nmajor25 commented on src/js/datadog.js
Pertaining to this: https://docs.datadoghq.com/real_user_monitoring/guide/browser-sdk-upgrade/#automatic-recording-of-sessions-sampled-for-session-replay

Does `datadogRum.startSessionReplayRecording();` need to be called in the `setUser()` function? Or can we remove that line of code and have it automatically record at the beginning of the session?

But maybe we need to keep that there until after the `setUser()` is called? I’m not sure.

2023-11-06 22:28 UTC, nmajor25 commented on src/js/datadog.js
If we remove `startSessionReplayRecording()`, we’ll need to set `sessionReplaySampleRate: 100`. The default for that changed from `100` => `0`. ([reference](https://docs.datadoghq.com/real_user_monitoring/guide/browser-sdk-upgrade/#default-session-replay-sampling-rate))  

Otherwise, it’d be set to `0` by default and no replays would be recorded.

2023-11-06 22:28 UTC, nmajor25 commented on src/js/datadog.js
If we need to keep using `startSessionReplayRecording()`, we’ll need to set the `startSessionReplayRecordingManually: true` init parameter.

2023-11-06 22:29 UTC, nmajor25 commented on src/js/datadog.js
There were also some small changes to the `beforeSend()` method. But I don't think they effect anything for us.

2023-11-07 05:57 UTC, paulfalgout requested changes

2023-11-07 05:57 UTC, paulfalgout commented on src/js/datadog.js
I think setting the manual would be ok.  There's very very little the user can do prior to bootstrap that we could glean from watching a session replay.  That way we're also only watching the session for a logged in user.

2023-11-07 18:46 UTC, nmajor25 commented on src/js/datadog.js
Ya that makes sense. I'll work on getting that updated. 

And I'll go through the change log again and make sure we're all good in terms of handling any other breaking changes.

2023-11-07 22:04 UTC, nmajor25 commented on src/js/datadog.js
Okay I just added the `startSessionReplayRecordingManually: true` init option.

Since we use `startSessionReplayRecording()`, my understanding is that we don't need to set `sessionReplaySampleRate: 100`. That's only used if the sessions recordings are automatically started when the session begins (without `startSessionReplayRecording()`)

2023-11-08 12:32 UTC, paulfalgout approved these changes

2023-11-08 12:32 UTC, merged