In patient modal, only use `patient_creation_form.form_id` when creating a new patient
RoundingWell/care-ops-frontend pull request #1229
Opened 2024-01-29 23:44 UTC by nmajor25

Shortcut Story ID: [sc-47386]

Not sure how I missed this, but this should have been addressed in the original PR for fixing these patient modal bugs: https://github.com/RoundingWell/care-ops-frontend/pull/1222.

If this org/workspace setting is set:

```js
{
  "id": "patient_creation_form",
  "attributes": {
    "value": {
      "form_id": "11111",
      "submit_text": "Continue to Form 11111"
    }
  }
}
```

The `form_id` and `submit_text` should only be used in the edit patient modal. Not the create new patient or view patient versions of the modal. 

https://github.com/RoundingWell/care-ops-frontend/pull/1222 fixed the wrongful usage of `submit_text`. But did not fix the wrongful usage of `form_id`, which is where the user is routed to after creating a new patient.

2024-01-29 23:46 UTC, nmajor25 commented on src/js/apps/globals/nav_app.js
> +            if (patientFormId && isForNewPatient) {
I wanted to use `&& patient.isNew()` here. But that always returns `false` in this context.

2024-01-30 16:34 UTC, paulfalgout requested changes

2024-01-30 16:34 UTC, paulfalgout commented on src/js/apps/globals/nav_app.js
> +            if (patientFormId && isForNewPatient) {
after the `saveAll` it wouldn't be new, but you can do the new check prior to the modal request..perhaps off of the clone

2024-01-30 16:41 UTC, nmajor25 commented on src/js/apps/globals/nav_app.js
> +            if (patientFormId && isForNewPatient) {
Good call, updated it to check `patientClone.isNew()`.

2024-01-30 16:46 UTC, paulfalgout approved these changes

2024-01-30 16:47 UTC, merged