Update eslint from `v8` => `v9`
RoundingWell/care-ops-frontend pull request #1266
Opened 2024-05-30 18:17 UTC by nmajor25

Shortcut Story ID: [sc-50941]

Also updated to `eslint-webpack-plugin`. Which needed to release a new version to be compatible with eslint v9.

2024-05-30 18:19 UTC, nmajor25 commented
Still looking into why the tests are borking.

2024-05-30 18:46 UTC, paulfalgout requested changes
The borking tests are just the linter failing on this line: https://github.com/RoundingWell/care-ops-frontend/blob/develop/src/js/services/forms.js#L106

It's saying the `(e)` should be `()`

2024-05-30 19:05 UTC, nmajor25 commented
Yep, good call. Think we should be good now 🤞

2024-05-30 19:10 UTC, paulfalgout requested changes

2024-05-30 19:10 UTC, paulfalgout commented on src/js/services/forms.js
> -    } catch (e) /* istanbul ignore next: Tested locally, test runner borks on CI */ {
the coverage drop is from the comment being removed

2024-05-30 20:47 UTC, nmajor25 commented on src/js/services/forms.js
> -    } catch (e) /* istanbul ignore next: Tested locally, test runner borks on CI */ {
Oops, added that back

2024-05-31 05:44 UTC, paulfalgout approved these changes

2024-05-31 05:44 UTC, merged