Support `CommentAdded` web socket notification in patient action sidebar
RoundingWell/care-ops-frontend pull request #1348
Opened 2024-11-05 18:43 UTC by nmajor25

Shortcut Story ID: [sc-56328]

2024-11-05 18:46 UTC, nmajor25 commented on src/js/apps/patients/sidebar/action-sidebar_app.js
When we receive a `CommentAdded` ws notification, we need to make an api request to get the full comment model, right? And then add it to the activity collection (events & comments combined into one collection)?

That was my assumption with this.

To do that I think we need to do the `subscribe()` directly in the `action-sidebar_app`. Instead of the flow app. But that means the action sidebar will handle the `CommentAdded` ws notification outside of the patient flow page.

2024-11-05 18:52 UTC, nmajor25 commented on test/integration/patients/patient/patient-flow.js
> +          message: 'New websocket comment.',
If we use this current implementation, this portion of the ws notification message isn't used.

2024-11-05 18:54 UTC, nmajor25 commented on src/js/apps/patients/sidebar/action-sidebar_app.js
I would imagine we'll run into the same situation with the `AttachmentAdded` notification.

2024-11-06 15:41 UTC, paulfalgout requested changes

2024-11-06 15:41 UTC, paulfalgout commented on src/js/apps/patients/sidebar/action-sidebar_app.js
nope.  subscribing within the sidebar will clear the subscription on the flow.  this action is already subscribed to.  Plus I think we should probably handle this on the action.. and if it passes the message itself do we need to fetch it from the API?  what data is missing?  If it's just a timestamp we can set it to now. Anything else we could probably just ask for it to be included on the comment.

2024-11-06 19:29 UTC, nmajor25 commented on src/js/apps/patients/sidebar/action-sidebar_app.js
The websocket notification looks like this: https://github.com/RoundingWell/care-ops-backend/blob/develop/tests/Notifications/Data/Messages/comment-added-message-structure.json.

If we have the comment contents. So if we had the `created_at` and clinician name included, we wouldn't need to fetch it via the api.

2024-11-06 22:49 UTC, nmajor25 commented on src/js/apps/patients/sidebar/action-sidebar_app.js
I'm going to close this PR and start a new one.

2024-11-06 22:49 UTC, closed without merging