Remove use of clinician first_name and last_name in favor of name
RoundingWell/care-ops-frontend pull request #138
Opened 2019-11-13 20:05 UTC by luketlancaster

- [x] Add the Clubhouse Story ID: [ch21384]

2019-11-13 20:07 UTC, luketlancaster commented
I just did a search for `first_name` and `last_name` and yanked all those out. Lemme know if you think I may have missed anything

2019-11-13 20:16 UTC, paulfalgout requested changes

2019-11-13 20:16 UTC, paulfalgout commented on src/js/views/patients/actions/actions_views.js
> +        template: hbs`{{far "user-circle"}}{{ short }}{{ name }}`,
roles have names. so this looks like an issue to me.  either we'll need to split the template here or make a templateContext helper that returns the appropriate result based on the model type

2019-11-13 20:16 UTC, paulfalgout commented on src/js/views/patients/sidebar/action/action-sidebar-activity-views.js
> +      name: _.trim(editor.get('name')),
shouldn't need the trims that's kinda legacy stuff from when on mainapp you could potentially not have one of the names

2019-11-13 20:16 UTC, paulfalgout commented on test/fixtures/config/clinicians.js
> +      name: `${ faker.name.firstName() } ${ faker.name.lastName() }`,
could be `faker.name.findName()`

2019-11-14 07:05 UTC, paulfalgout commented on test/integration/patients/patient/dashboard.js
> +      .should('contain', 'Clinician McTester');
I updated these to be the full name.  I know they're not displayed entirely, but that's what's in there.

2019-11-14 07:06 UTC, paulfalgout approved these changes

2019-11-14 07:10 UTC, merged