Display patient flows
RoundingWell/care-ops-frontend pull request #188
Opened 2020-01-09 17:40 UTC by LisaManresa

- [x] Add the Clubhouse Story ID: [ch21609]

2020-01-09 18:04 UTC, paulfalgout requested changes

2020-01-09 18:04 UTC, paulfalgout commented on src/js/views/patients/patient/dashboard/add-action.scss
> +  .picklist__flow-item .icon {
I think this should be `add-action` prefixed.  `picklist` makes it look like it'd be found in the picklist module scss.

2020-01-09 18:04 UTC, paulfalgout commented on src/js/views/patients/patient/dashboard/add-workflow_views.js
> +const ItemTemplate = hbs`<span class="{{#if isFar}}picklist__action-item{{else}}picklist__flow-item{{/if}}">{{#if isFar}}{{far iconType}}{{else}}{{fas iconType}}{{/if}} <a>{{ name }}</a></span>`;
I don't like reusing `isFar` here it means "is fontawesome regular" we might want a different check for the type.  Is the __action-item class used?

2020-01-09 18:04 UTC, paulfalgout commented on src/js/views/patients/patient/dashboard/add-workflow_views.js
> +const ItemTemplate = hbs`<span class="{{#if isFar}}picklist__action-item{{else}}picklist__flow-item{{/if}}">{{#if isFar}}{{far iconType}}{{else}}{{fas iconType}}{{/if}} <a>{{ name }}</a></span>`;
actually should change even be in this PR?

2020-01-09 18:04 UTC, paulfalgout commented on test/fixtures/config/flows.js
> +      due_date: moment(faker.date.between(
I don't think flows have `due_date` or `duration` but will have a `created_at`

2020-01-09 18:09 UTC, LisaManresa commented on src/js/views/patients/patient/dashboard/add-workflow_views.js
> +const ItemTemplate = hbs`<span class="{{#if isFar}}picklist__action-item{{else}}picklist__flow-item{{/if}}">{{#if isFar}}{{far iconType}}{{else}}{{fas iconType}}{{/if}} <a>{{ name }}</a></span>`;
I can remove it. Just figured it was easy pickings, but I can leave it for @luketlancaster's PR if that's the more logical place for it

2020-01-09 19:00 UTC, luketlancaster commented on test/support/api/flows.js
> +  // cy.routeProgramByAction();
this needed?

2020-01-09 19:03 UTC, luketlancaster commented on src/js/views/patients/patient/data-events/action-item.hbs
> +    </td>
couplea nits to pick: does this need to be indented? And also should we throw in `{{~ remove_whitespace ~}}` like what we have in the `flow-item` template?

2020-01-09 19:39 UTC, paulfalgout commented
The tests are failing consistently.. seems like a legit issue.

2020-01-09 19:57 UTC, LisaManresa commented
Yup, I think I got them resolved now. Running coverage locally and checking the coverage report now.

2020-01-10 07:36 UTC, paulfalgout commented on test/integration/admin/programs/sidebar/flow-sidebar.js
> +      .routeProgramFlowActions(fx => {
👍 ah flake.  good catch

2020-01-10 07:37 UTC, paulfalgout commented on test/support/api/flows.js
> +Cypress.Commands.add('routePatientFlows', (mutator = _.identity, patientId) => {
it probably does make sense to create some sort of data generator function that these two can share at some point as you were moving towards earlier.. but we can circle back around.

2020-01-10 07:37 UTC, paulfalgout approved these changes

2020-01-10 07:38 UTC, merged