Support full page form view in form app
RoundingWell/care-ops-frontend pull request #213
Opened 2020-01-28 18:22 UTC by LisaManresa

- [x] Add the Clubhouse Story ID: [ch21687]

A first pass at toggling the full width view for forms. Need to review behaviors with Mark to confirm they are correct.

This uses 2 different properties on the state to keep track:
1. `sidebar`: The view/app that is currently active in the sidebar, regardless of whether it is collapsed or not.
2. `fullPageForm`: Keeps track of whether the form is expanded or not

As of now, if the action sidebar button is clicked while the form is expanded, we compress the form and display the action sidebar (Even if the previously displayed sidebar was the patient sidebar). This is the behavior I need to review with Mark.

2020-01-28 18:44 UTC, paulfalgout requested changes
I think the previous version of this was just using the state as a flag, but I think we might be better served here by reacting to the state change where the user interactions all just call a single `setState` function (or `toggleState`) and then based on state change events we re-render or something like that which run through the same group of logic based on the state.  I also think it may be better to store a flag (or flags) in the state rather than an app.  If we do go in the direction of being able to open the form app in various states, it'll be easier to pass a set of flags than it will be to determine which sidebar app should be stored in the state.

2020-01-28 18:44 UTC, paulfalgout commented on src/js/apps/forms/form/form_app.js
> +      'sidebar': false,
don't need to be `'`'d

2020-01-28 18:44 UTC, paulfalgout commented on src/js/apps/forms/form/form_app.js
> +      'sidebar': sidebar,
same here with the `'`

2020-01-28 18:44 UTC, paulfalgout commented on src/js/views/forms/form/form_views.js
> +  onClickExpandButton() {
can be removed?

2020-01-28 18:44 UTC, paulfalgout commented on src/js/apps/forms/form/form_app.js
> +    this.setState('fullPageForm', !this.getState('fullPageForm'));
I think there's a `this.toggleState('fullPageForm')`

2020-01-29 17:43 UTC, paulfalgout approved these changes
Is this mark approved?

2020-01-29 17:45 UTC, LisaManresa commented
Yup. Screen shared with Mark yesterday and went over the functionality. Added in the tooltips at his request.

2020-01-29 17:50 UTC, LisaManresa commented
[ch21920]

2020-01-29 17:51 UTC, merged