Fix flow status icon on patient dashboard
RoundingWell/care-ops-frontend pull request #224
Opened 2020-02-06 23:54 UTC by LisaManresa

- [x] Add the Clubhouse Story ID: [ch21985]

2020-02-06 23:58 UTC, sofiaroundingwell approved these changes

2020-02-07 08:13 UTC, paulfalgout requested changes
Might be ok to get this in for the release, but we should readdress this.  We handle this same situation differently for workflows__flow-status and we're not handling flow-action--attachment which I imagine has the same issue.

2020-02-07 08:13 UTC, paulfalgout commented on src/js/views/patients/patient/patient.scss
> +  padding: 0 9px;
this should probably be `padding: 8px` and `border: 1px solid transparent;`

2020-02-07 16:24 UTC, paulfalgout commented
Since this is in the other PR and already in release we can handle it over there.

2020-02-07 16:24 UTC, closed without merging