Display 403 failures on action/flow delete
RoundingWell/care-ops-frontend pull request #344
Opened 2020-08-13 18:54 UTC by LisaManresa

- [x] Add the Clubhouse Story ID: [ch23105]

2020-08-13 18:54 UTC, LisaManresa commented
This is pending what we decide to do with worklist bulk delete. But we can get 👀  on everything else

2020-08-17 12:48 UTC, paulfalgout requested changes

2020-08-17 12:48 UTC, paulfalgout commented on src/js/apps/patients/worklist/worklist_app.js
> +        this.selected.destroy({ wait: true })
I think we should revert this, so it's clear _something_ needs to be done.. I don't think this'd what it'd be if we do this.

2020-08-17 12:48 UTC, paulfalgout commented on test/integration/patients/sidebar/flow-sidebar.js
> -    cy
should this get removed?

2020-08-17 13:44 UTC, LisaManresa commented on test/integration/patients/sidebar/flow-sidebar.js
> -    cy
No it should not.

2020-08-17 14:26 UTC, paulfalgout approved these changes

2020-08-17 14:26 UTC, merged