Update created/due labels
RoundingWell/care-ops-frontend pull request #424
Opened 2021-01-07 23:03 UTC by luketlancaster

- [x] Add the Clubhouse Story ID: [ch23968]
- [ ] Add QA tasks

2021-01-07 23:03 UTC, luketlancaster commented
using the extra 🐴 power of the ☁️ to run the tests

2021-01-08 13:28 UTC, paulfalgout requested changes

2021-01-08 13:28 UTC, paulfalgout commented on src/js/i18n/en-US.yml
> +            createdAt: Added
One thing that this surfaced...  We should change all of the "Last Updated"s to just "Updated". In this case if there are any keys that use "last" we should remove that.

2021-01-08 19:05 UTC, paulfalgout approved these changes

2021-01-11 14:22 UTC, paulfalgout approved these changes

2021-01-11 14:22 UTC, merged