Schedule List View
RoundingWell/care-ops-frontend pull request #447
Opened 2021-01-28 19:32 UTC by LisaManresa

- [x] Add the Clubhouse Story ID: [ch24238]

2021-01-28 21:00 UTC, paulfalgout requested changes
looks pretty good.

2021-01-28 21:00 UTC, paulfalgout commented on src/js/views/patients/schedule/schedule_views.js
> +  buildChildView(child, ChildViewClass) {
viewOptions is probably better here

2021-01-28 21:00 UTC, paulfalgout commented on src/js/views/patients/schedule/schedule_views.js
> +    // nullVal of 24 to ensure null due_time is last in list and due_time never exceeds 23:59:59
interesting.  works for me

2021-01-28 21:00 UTC, paulfalgout commented on src/js/views/patients/schedule/schedule_views.js
> +  regions: {
is this in use?

2021-01-28 21:00 UTC, paulfalgout commented on src/js/views/patients/schedule/schedule_views.js
> +      rowspan: this.collection.length,
not in use?

2021-01-28 21:00 UTC, paulfalgout commented on src/js/views/patients/schedule/schedule_views.js
> +      isToday: date.isSame(today, 'year') && date.isSame(today, 'month') && today.date() === date.date(),
`date.isSame(today, 'day')` should work here.  `isSame(..'month'` also checks the year

2021-01-28 21:00 UTC, paulfalgout commented on src/js/apps/patients/schedule/schedule_app.js
> +      collection: this.collection,
is this the only use of `this.collection`?  Might not need to attach it to the app

2021-01-28 21:00 UTC, paulfalgout commented on src/js/views/patients/schedule/schedule.scss
> +.schedule__filter-date {
is this in use?

2021-01-28 21:00 UTC, paulfalgout commented on src/js/views/patients/schedule/schedule.scss
> +.schedule__filter-date {
There's also a case to be made that this could just be `..flex--end-row`

2021-01-28 21:00 UTC, paulfalgout commented on src/js/views/patients/schedule/schedule.scss
>  .schedule-list__header {
I think we should go ahead and make here down in a `schedule-list.scss` file.  They're highly related, but I think the block name being the filename is proving useful.

2021-01-28 21:00 UTC, paulfalgout commented on src/js/views/patients/schedule/schedule_views.js
> +  childViewContainer: '[data-actions-region]',
historically we've used `.js-` selector for these, but they're kinda region-y..  I kinda like it.. more obvious in the templates. hmm

2021-01-28 22:04 UTC, LisaManresa commented on src/js/views/patients/schedule/schedule_views.js
> +    // nullVal of 24 to ensure null due_time is last in list and due_time never exceeds 23:59:59
It works, but the empty ones are sorted to the top of the list if we use ascending sort. This was a quick way to sort them to the bottom instead.

2021-01-28 22:05 UTC, LisaManresa commented on src/js/apps/patients/schedule/schedule_app.js
> +      collection: this.collection,
It is now. I'll remove. We'll be using `this.collection` all over the place with bulk edit, though.

2021-01-28 22:07 UTC, LisaManresa commented on src/js/views/patients/schedule/schedule.scss
> +.schedule__filter-date {
Yeah this isn't needed at all now. Will remove

2021-01-28 22:12 UTC, LisaManresa commented on src/js/views/patients/schedule/schedule_views.js
> +  childViewContainer: '[data-actions-region]',
I kind of prefer the region reference as well. But happy to change it to fit the patter if you prefer.

2021-01-29 07:32 UTC, paulfalgout commented on src/js/views/patients/schedule/schedule_views.js
> +  childViewContainer: '[data-actions-region]',
let's switch to the region selector idea and refactor older ones if we see them

2021-01-29 07:43 UTC, paulfalgout requested changes
Looks good to me. Just one small thing and :shipit:

2021-01-29 07:43 UTC, paulfalgout commented on src/js/views/patients/schedule/schedule_views.js
> +      isToday: date.isSame(today, 'month') && date.isSame(today, 'day'),
This is still redundant.  `dayjs('2021-02-01').isSame(dayjs('2021-01-01'), 'day') === false`.  `isSame(today, 'day')` checks year, month, and day.

2021-01-29 15:58 UTC, LisaManresa commented
Tests were flakey because of the dynamic dates, so I made some modifications to make them more stable.

2021-01-29 16:03 UTC, LisaManresa commented
Actually, let's hold off on merging this for now. I'm going over a few design items with Mark and would like to add them to this PR

2021-01-29 17:53 UTC, LisaManresa commented
Ok, style changes applied.

2021-01-29 19:26 UTC, paulfalgout approved these changes

2021-01-29 19:26 UTC, merged