Update Font Awesome to version 6.1.0
RoundingWell/care-ops-frontend pull request #654
Opened 2022-03-17 22:37 UTC by nmajor25

Shortcut Story ID: [sc-28100]

This pull request updates the Font Awesome dependency version from v5 to v6. Version 6 should be backwards compatible. So styling in the app should not be effected.

Since some icons were renamed in Version 6, it caused a number of Cypress tests to break. Therefore, this pull request also includes fixes for those tests.

[Full list of changed icon names](https://fontawesome.com/docs/web/setup/upgrade/whats-changed#icons-renamed-in-version-6).

2022-03-18 07:52 UTC, paulfalgout requested changes
Ah ok so some of the class names applied on the svgs have changed.  This is actually problematic.  The tests needed to be updated, but we also need to look through all of our styles for any user of these classes to make sure they're updated as well.  For instance search for `.fa-expand-alt` and you should find that one of the widget styles refers to this class.

2022-03-18 14:31 UTC, nmajor25 commented
Missed those, okay I'll go through and get those classes updated.

2022-03-18 19:43 UTC, nmajor25 commented on src/js/views/globals/prelogin/prelogin.css
> +.prelogin__continue-button .fa-right-to-bracket {
We could keep this the same and it wouldn't modify any of the styling. But I figured we'd update it to match the new name Font Awesome gave the icon.

It coincides with the Handlebars template in the `src/js/views/globals/prelogin/login-prompt.hbs` file.

2022-03-18 19:44 UTC, nmajor25 commented on src/js/views/globals/prelogin/login-prompt.hbs
> +  <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="right-to-bracket" role="img" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 512 512" class="svg-inline
Coincides with the change made to the CSS selector change in the `src/js/views/globals/prelogin/prelogin.css` file.

2022-03-20 18:54 UTC, paulfalgout approved these changes

2022-03-20 18:54 UTC, merged