Create new form service for saving to PDF
RoundingWell/care-ops-frontend pull request #727
Opened 2022-06-22 16:28 UTC by nmajor25

Shortcut Story ID: [sc-29317]

2022-06-23 11:22 UTC, paulfalgout requested changes

2022-06-23 11:22 UTC, paulfalgout commented on src/js/index.js
> +  const isFormService = /^\/formservice\//.test(location.pathname);
OK I found out that puppeteer can just intercept the header and inject the token, so we probably don't need to handle auth with this app at all.

I think we can actually put this right on line 68 even above the cypress check:
```js
if (isFormService) startFormService();
```

No other auth stuff is needed here.

This will mean we can't test this on our sandboxes without some form of puppeteer, but Cypress should likely still work as long as we're properly stubbing all of the requested endpoints.

2022-06-23 14:49 UTC, nmajor25 commented on src/js/index.js
> +  const isFormService = /^\/formservice\//.test(location.pathname);
Okay, just updated and pushed those changes.

2022-06-27 17:15 UTC, nmajor25 commented on src/js/index.js
> +function startAuth() {
Just removed an unused function parameter. Forgot to remove it in the last commit.

2022-06-27 17:20 UTC, nmajor25 commented on test/integration/formservice/formservice.js
> +  });
Do we need this test form to have all three of these input fields?

We could just trim it down to just the one input field and the test would serve the same purpose, right? Would be cleaner and less lines of code.

2022-06-27 17:42 UTC, paulfalgout requested changes
Pretty much done

2022-06-27 17:42 UTC, paulfalgout commented on test/integration/formservice/formservice.js
> +  });
Nope.  In fact you can probably just grab a form from the fixtures for the definition.

It'd be something like: 
```js
  cy
    .fixture('test/form-definition').as('fxTestFormDefinition');

win.postMessage({ message: 'form:pdf', args: {
  definition: this.fxTestFormDefinition,
  ...
```
But it might be simpler to just simplify the form to one input.

2022-06-27 18:38 UTC, paulfalgout approved these changes

2022-06-27 18:40 UTC, nmajor25 commented on test/integration/formservice/formservice.js
> +  });
Just went with reducing it to one input.

2022-06-27 18:46 UTC, merged