Extend the patient dashboard to be the full height of the page
RoundingWell/care-ops-frontend pull request #734
Opened 2022-06-30 22:17 UTC by nmajor25

Shortcut Story ID: [sc-29467]

The patient sidebar on the patient dashboard and flow page doesn't extend to the full height of the page. This was first noticed on a long version of the flow page, where its left border stopped midway (screenshot below).

This pull request updates the CSS so it extends to the full height of the browser window. Regardless of content length.

<img width="115" alt="image (1)" src="https://user-images.githubusercontent.com/35355575/176787704-7b175f01-aea6-4941-8ac7-17a5e565e992.png">
.

2022-07-01 15:23 UTC, nmajor25 commented
@paulfalgout just some background info on how I came to this solution.

Per your suggestion off of GitHub, my initial attempt at this was to add `display: table` to `.patient__layout`, remove the left border from the patient sidebar, and then add a right border to `.patient__layout`.

That made the border extend the full height of the page and fixed the issue for the patient dashboard and flow pages.

But this causes some UI issues for the patient sidebar used on the form page. When the border is added there, it remains visible even when the sidebar is collapsed. Although it wasn't super noticeable, it still didn't feel optimal.

After some additional investigating, I narrowed down the issue to the overflow being applied to the`.patient__frame`. Not entirely sure why, but this was stopping the content and sidebar from extending the full page height.

I replaced those overflow styles with `flex: 1;` (tells the elements to fill the available space) and then added `overflow-y: auto;` to `.app-frame__content`.

This seemed to have fixed the issue. The patient sidebars now take the full height of the page, regardless of content length.

And I went through the other pages in the app to ensure that the change to `.app-frame__content` didn't break the layout or anything else in the UI. From what I can tell, everything still looks/works normally.

2022-07-01 15:26 UTC, nmajor25 commented on src/js/views/programs/program/flow/program-flow.scss
>  }
This page doesn't use the patient sidebar. But I updated this to remain consistent with what's used for the other pages (i.e. `.patient__frame`, `.patient-flow__frame`, etc.).

Same goes for `src/js/views/programs/program/program.scss`.

2022-07-07 13:29 UTC, paulfalgout requested changes
Nice. This is a better solution than I would have imagined it would be.  flex FTW.  
Honestly our current app frame styles have some history in having support old-IE so I'm not at all surprised if there are some flex solutions that would work better at a lower level.

2022-07-07 13:30 UTC, paulfalgout approved these changes

2022-07-07 13:30 UTC, merged