Custom filter sidebar tweaks
RoundingWell/care-ops-frontend pull request #842
Opened 2022-11-07 19:58 UTC by nmajor25

Shortcut Story ID: [sc-32018]

Two changes in this PR:

1. Set `isSelected: true` for each filter's droplist in the filters sidebar. (This adds an input field where the picklist items can be filtered)
2. Sort the filters alphabetically by their name. But keep the `Groups` filter at the top.

2022-11-07 20:04 UTC, nmajor25 commented on src/js/views/patients/sidebar/filters/filters-sidebar_views.js
> +      placeholderText: `${ this.getOption('filterTitle') }...`,
Better way to do this?

2022-11-07 20:04 UTC, nmajor25 commented on test/integration/patients/worklist/schedule.js
> +            },
Added this filter. I use it to verify that the filters are alphabetically sorted:

1. Group
2. Insurance Plans
3. Team

If the filters aren't alphabetically sorted, `Team` would be positioned before `Insurance Plans`.

2022-11-07 20:04 UTC, nmajor25 commented on src/js/views/patients/sidebar/filters/filters-sidebar_views.js
> +const i18n = intl.patients.sidebar.filters.filtersSidebarViews;
Just added this to make things more concise when accessing `intl.patients.sidebar.filters.filtersSidebarViews` values from the `/i18n/en-US.yml` file.

2022-11-07 20:06 UTC, nmajor25 commented on test/integration/patients/worklist/schedule.js
> +      .should('have.attr', 'placeholder', 'Group...');
Simply confirms that `isSelected: true` input exists in the droplist and that the correct placeholder is used (name of the custom filter).

2022-11-08 14:44 UTC, paulfalgout requested changes

2022-11-08 14:44 UTC, paulfalgout commented on src/js/views/patients/sidebar/filters/filters-sidebar_views.js
> +      itemTemplate: hbs`<div>{{matchText name query}}</div>`,
`attr: 'name'` is preferred here

2022-11-08 14:44 UTC, paulfalgout commented on src/js/views/patients/sidebar/filters/filters-sidebar_views.js
> +      placeholderText: `${ this.getOption('filterTitle') }...`,
probably correct

2022-11-08 16:09 UTC, nmajor25 commented on src/js/views/patients/sidebar/filters/filters-sidebar_views.js
> +      itemTemplate: hbs`<div>{{matchText name query}}</div>`,
Yup that's easier, just updated that.

2022-11-08 16:13 UTC, paulfalgout approved these changes

2022-11-08 16:26 UTC, merged