Click+shift multi select for schedule items
RoundingWell/care-ops-frontend pull request #871
Opened 2022-12-08 23:47 UTC by nmajor25

Shortcut Story ID: [sc-32186]

When an item is selected in the schedule, allow a user to `shift`+`click` to select multiple list items between the two.

2022-12-08 23:54 UTC, nmajor25 commented on src/js/views/patients/schedule/schedule_views.js
> +  },
To get the correct index position of a selected list item, I needed to create a flattened version of the collection and sort those actions by date.

Convert this:

```js
[
  {
    day: {
      actions: [ {action}, {action} ]
    }
  },
  {
    day: {
      actions: [ {action} ]
     }
   }
]
```

Into this:

```js
[
  {action}, {action}, {action}
]
```

Where actions are sorted by due day and time.

2022-12-12 15:30 UTC, paulfalgout requested changes
I think this is looking pretty close.

2022-12-12 15:30 UTC, paulfalgout commented on src/js/views/patients/schedule/schedule_views.js
> +    const collectionJSON = this.collection.toJSON();
so the this view is being passed `this.collection.groupByDate()` as the collection.  I wonder if we should also pass it the original collection?  Then we just need to do what's in `sortDueAsc`

2022-12-12 20:49 UTC, nmajor25 commented on src/js/views/patients/schedule/schedule_views.js
> +    const collectionJSON = this.collection.toJSON();
Updated to use the original collection in my latest push. I think I have it simplified as much as possible... open to suggestions though.

2022-12-12 21:05 UTC, paulfalgout commented on src/js/views/patients/schedule/schedule_views.js
> +        return alphaSort('asc', a.get('due_time'), b.get('due_time'), '24');
why the `24`?  is there a bug in our worklist sort?

2022-12-12 21:11 UTC, nmajor25 commented on src/js/views/patients/schedule/schedule_views.js
> +        return alphaSort('asc', a.get('due_time'), b.get('due_time'), '24');
I added it to match the `viewComparator` used on the `DayListView`. To ensure the sorting method is same here vs. on the view.

Not sure about worklist. Will investigate.

2022-12-12 22:04 UTC, nmajor25 commented on src/js/views/patients/schedule/schedule_views.js
> +        return alphaSort('asc', a.get('due_time'), b.get('due_time'), '24');
On the worklist, actions with `due_time: null` are placed either above or below actions that possess a `due_time`. Depends whether the sort is `asc` or `desc`. Do we want `due_time: null` actions to always be on the bottom? 

Example of `ascending` order:

![Screen Shot 2022-12-12 at 3 46 41 PM](https://user-images.githubusercontent.com/35355575/207161861-6b3baf01-a580-459f-8d9f-bb07a6f83e98.png)

_Note: `Due: Newest - Oldest` and `Due: Oldest - Newest` don't seem to be sorting in the correct directions. Think those need to be switched._

Compared to the schedule, where those are on the bottom:

![Screen Shot 2022-12-12 at 3 47 27 PM](https://user-images.githubusercontent.com/35355575/207161839-5b3eb16d-bd60-4a84-883b-db090ccd1ac8.png)

2022-12-13 14:09 UTC, paulfalgout commented on src/js/views/patients/schedule/schedule_views.js
> +        return alphaSort('asc', a.get('due_time'), b.get('due_time'), '24');
I _think_ the sort order is correct, though it is confusing.. but consider over due dates.. those would be oldest and would be at the top.. and the "newest" is the latest due.. But yeah the `24` seems better in this case I suppose..  so does the due date sort match the worklist where "oldest" indicates either overdue or soonest to be due?  seems like yes?

2022-12-13 16:22 UTC, paulfalgout approved these changes

2022-12-13 16:27 UTC, nmajor25 commented on src/js/views/patients/worklist/worklist_views.js
> +        return alphaSort('asc', a.model.get('due_time'), b.model.get('due_time'), '24');
When sorting the row for the `Due: Oldest - Newest` option, this forces actions with a `due_date` to be on top of actions without one (`due_date: null`).

The `'24'` is not needed to achieve this for the `Due: Newest - Oldest` sort option.

2022-12-13 16:28 UTC, merged